
# Site settings
title: Michael Seemann
sub_title: FullStack Developer
key_words: 
  - AngularJS
  - Java 
  - JavaScript
  - TypeScript 
  - MongoDB 
  - Node.js 
  - iOS
  - Docker
  
email: apps@mseemann.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mseemann.github.io/" # the base hostname & protocol for your site
github_username:  mseemann
github_url: https://github.com/mseemann
repository: mseemann

# Build settings
markdown: kramdown

## Gem
gems:
  - jekyll-github-metadata
  
# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show