
# Site settings
title: Michael Seemann
sub_title: FullStack Developer
key_words: 
  - AngularJS
  - Java 
  - JavaScript
  - TypeScript 
  - MongoDB 
  - Node.js 
  - Tomcat
  - Apache
  - Nginx
  - iOS
  - Docker
  - Cordova
  - Ionic
  
email: apps@mseemann.de
description: >
  My name is Michael Seemann - i am a so called full stack developer. Meaning i don't care 
  about frontend or backend development - i just care about writing apps that people can
  use in the simplest possible way. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mseemann.github.io/" # the base hostname & protocol for your site
github_username:  mseemann
github_url: https://github.com/mseemann
repository: mseemann
excerpt_separator: <!-- more -->
# Build settings
markdown: kramdown

## Gem
gems:
  - jekyll-github-metadata
  
# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show
